name: CI - Tests and Build Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test with Dynamic Badge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: run_tests
        run: |
          npm run test

      - name: Create badges folder
        run: mkdir -p badges

      - name: Generate build badge
        if: success()
        run: |
          curl -o badges/build.svg "https://img.shields.io/badge/Build-Passing-brightgreen.svg"

      - name: Generate build badge on failure
        if: failure()
        run: |
          curl -o badges/build.svg "https://img.shields.io/badge/Build-Failing-red.svg"

      - name: Commit badges
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update build badge"
          add: "badges/build.svg"
