name: Generate Coverage Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests and collect coverage
        run: npm run test

      - name: Generate coverage badge
        run: |
          mkdir -p badges
          COVERAGE=$(node -p "Math.round(require('./coverage/coverage-final.json').total.lines.pct)")
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="120" height="20"><rect width="120" height="20" fill=\"#555\"/><rect x=\"60\" width=\"60\" height=\"20\" fill=\"#4c1\"/><text x=\"30\" y=\"14\" fill=\"#fff\" font-family=\"Verdana\" font-size=\"11\">coverage</text><text x=\"80\" y=\"14\" fill=\"#fff\" font-family=\"Verdana\" font-size=\"11\">'$COVERAGE'%</text></svg>' > badges/coverage.svg

      - name: Commit badge
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update coverage badge"
          add: "badges/coverage.svg"
