name: Generate Coverage Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests and collect coverage
        run: npm run test

      - name: Generate coverage badge with Shields.io
        run: |
          mkdir -p badges
          COVERAGE=$(node -p "
            const coverage = require('./coverage/coverage-final.json');
            const files = Object.values(coverage);
            const { totalStatements, coveredStatements } = files.reduce((acc, file) => {
              const statements = Object.keys(file.statementMap || {}).length;
              const covered = Object.values(file.s || {}).filter(v => v > 0).length;
              acc.totalStatements += statements;
              acc.coveredStatements += covered;
              return acc;
            }, { totalStatements: 0, coveredStatements: 0 });
            Math.round((coveredStatements / totalStatements) * 100);
          ")

          if [ $COVERAGE -ge 90 ]; then
            COLOR=brightgreen
          elif [ $COVERAGE -ge 75 ]; then
            COLOR=yellow
          else
            COLOR=red
          fi

          echo "Coverage: $COVERAGE%"
          curl -o badges/coverage.svg "https://img.shields.io/badge/Coverage-${COVERAGE}%25-${COLOR}.svg"

      - name: Commit badge
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update coverage badge"
          add: "badges/coverage.svg"
